export const PRIMARY = "#157CFC"
export const TABLE_GRAY_COLOR = "#9ca3af"

export const TABLE_ROW_BACKGROUND_COLOR = "#1f2937"
export const TABLE_HEADER_BACKGROUND_COLOR = "#374151"
export const TABLE_HEADER_COLOR = "#9ca3af"

export const RATING_10_COLOR = "#3b82f6"
export const RATING_9_COLOR = "#7dd3fc"
export const RATING_8_COLOR = "#15803d"
export const RATING_7_COLOR = "#22c55e"
export const RATING_6_COLOR = "#86efac"
export const RATING_5_COLOR = "#dcfce7"
export const RATING_4_COLOR = "#fde047"
export const RATING_3_COLOR = "#eab308"
export const RATING_2_COLOR = "#fda4af"
export const RATING_1_COLOR = "#f43f5e"
export const RATING_0_COLOR = "#be123c"
